title: The Awesome Documentation Place
description: This is where dev teams excel!
theme: just-the-docs

url: https://github.com/SteffenHvidPWT/BIB/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
