title: The Awesome Documentation Place
description: This is where dev teams excel!
theme: just-the-docs

url: https://github.com/SteffenHvidPWT/BIB/

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav_external_links:
  - title: Just the Docs on GitHub
    url: https://github.com/just-the-docs/just-the-docs
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
