name: CISTAT

on:
  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Build with Jekyll
        run: bundle exec jekyll build

      - name: Create ZIP of site
        run: |
          cd _site
          zip -r ../jekyll_site.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: jekyll_site
          path: jekyll_site.zip

  push:
    name: Push packages
    runs-on: ubuntu-latest
    needs: build
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: jekyll_site

      - name: "Push all packages to: nuget.pkg.github.com"
        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/SteffenHvidPWT/index.json
